dist: bionic

env:
  - PYTHON_VERSION=3.6 TENANT_SCHEMAS="django-tenant-schemas"
  - PYTHON_VERSION=3.7 TENANT_SCHEMAS="django-tenant-schemas"
  - PYTHON_VERSION=3.8 TENANT_SCHEMAS="django-tenant-schemas"

  - PYTHON_VERSION=3.6 TENANT_SCHEMAS="django-tenants"
  - PYTHON_VERSION=3.7 TENANT_SCHEMAS="django-tenants"
  - PYTHON_VERSION=3.8 TENANT_SCHEMAS="django-tenants"

services:
  - docker

script: "./run-tests"
