language: python
python:
  - "3.6"

dist: bionic

env:
  - TENANT_SCHEMAS="django-tenant-schemas"
  - TENANT_SCHEMAS="django-tenants"

install:
  - "pip install \"Django${DJANGO_SPEC}\" \"celery${CELERY_SPEC}\" \"${TENANT_SCHEMAS}\""
  - pip install -r requirements.txt -e .

services:
  - docker

script: "./run-tests"
